// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLl9_gECyJCmn9bUx8hJw28lTljHPdQI',
    appId: '1:393539643598:web:a61e196c26279face2c89f',
    messagingSenderId: '393539643598',
    projectId: 'flutterfierbase-9cd26',
    authDomain: 'flutterfierbase-9cd26.firebaseapp.com',
    storageBucket: 'flutterfierbase-9cd26.firebasestorage.app',
    measurementId: 'G-46B0D7K0QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_v_8c2EThRQ7GGt3rK5BMuwd34MXXeIo',
    appId: '1:393539643598:android:486f10e9ddbe6239e2c89f',
    messagingSenderId: '393539643598',
    projectId: 'flutterfierbase-9cd26',
    storageBucket: 'flutterfierbase-9cd26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCMpGzDRofcVr16e0EBCrxvQUcD2fK1xg',
    appId: '1:393539643598:ios:914cb093b6dd95a6e2c89f',
    messagingSenderId: '393539643598',
    projectId: 'flutterfierbase-9cd26',
    storageBucket: 'flutterfierbase-9cd26.firebasestorage.app',
    iosBundleId: 'com.example.fierbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCMpGzDRofcVr16e0EBCrxvQUcD2fK1xg',
    appId: '1:393539643598:ios:914cb093b6dd95a6e2c89f',
    messagingSenderId: '393539643598',
    projectId: 'flutterfierbase-9cd26',
    storageBucket: 'flutterfierbase-9cd26.firebasestorage.app',
    iosBundleId: 'com.example.fierbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALLl9_gECyJCmn9bUx8hJw28lTljHPdQI',
    appId: '1:393539643598:web:313b92bdd2f6f7a0e2c89f',
    messagingSenderId: '393539643598',
    projectId: 'flutterfierbase-9cd26',
    authDomain: 'flutterfierbase-9cd26.firebaseapp.com',
    storageBucket: 'flutterfierbase-9cd26.firebasestorage.app',
    measurementId: 'G-WK7GP6GP66',
  );
}
